[project]
name = "torch-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.5",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
]
